version: "3"

services:

  #
  # Build only
  #
  build-base:
    container_name: build-base
    image: $LOCAL_IMAGE
    build:
      context: ../
      dockerfile: ./local/Dockerfile
    command: "true"

  #
  # Build only
  #
  build-builder:
    container_name: build-builder
    image: $LOCAL_IMAGE
    stdin_open: true
    tty: true
    environment:
      DOCKER_PUSH: "${DOCKER_PUSH:-0}"
      DOCKER_USERNAME: $DOCKER_USERNAME
      DOCKER_PASSWORD: $DOCKER_PASSWORD
      TARGET_IMAGE_BUILDER: $TARGET_IMAGE_BUILDER
      TARGET_IMAGE_API: $TARGET_IMAGE_API
      TARGET_IMAGE_APP: $TARGET_IMAGE_APP
      TARGET_TAG_SUFFIX: $TARGET_TAG_SUFFIX
      PROJECT_NAME: $BUILDER_PROJECT_NAME
      PROJECT_TAG: $BUILDER_PROJECT_TAG
      PROJECT_TAG_ALIASES: $PROJECT_TAG_ALIASES
    privileged: true
    depends_on:
      - build-base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  #
  # Build API
  #
  build-api:
    container_name: build-api
    image: $LOCAL_IMAGE
    environment:
      DOCKER_PUSH: "${DOCKER_PUSH:-0}"
      DOCKER_USERNAME: $DOCKER_USERNAME
      DOCKER_PASSWORD: $DOCKER_PASSWORD
      TARGET_IMAGE_BUILDER: $TARGET_IMAGE_BUILDER
      TARGET_IMAGE_API: $TARGET_IMAGE_API
      TARGET_IMAGE_APP: $TARGET_IMAGE_APP
      TARGET_TAG_SUFFIX: $TARGET_TAG_SUFFIX
      BUILDER_IMAGE: $BUILDER_IMAGE
      PROJECT_NAME: $API_PROJECT_NAME
      PROJECT_TAG: $API_PROJECT_TAG
      PROJECT_TAG_ALIASES: $PROJECT_TAG_ALIASES
    privileged: true
    depends_on:
      - build-base
      - build-builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  #
  # Build APP
  #
  build-app:
    container_name: build-app
    image: $LOCAL_IMAGE
    environment:
      DOCKER_PUSH: "${DOCKER_PUSH:-0}"
      DOCKER_USERNAME: $DOCKER_USERNAME
      DOCKER_PASSWORD: $DOCKER_PASSWORD
      TARGET_IMAGE_BUILDER: $TARGET_IMAGE_BUILDER
      TARGET_IMAGE_API: $TARGET_IMAGE_API
      TARGET_IMAGE_APP: $TARGET_IMAGE_APP
      TARGET_TAG_SUFFIX: $TARGET_TAG_SUFFIX
      BUILDER_IMAGE: $BUILDER_IMAGE
      PROJECT_NAME: $APP_PROJECT_NAME
      PROJECT_TAG: $APP_PROJECT_TAG
      PROJECT_TAG_ALIASES: $PROJECT_TAG_ALIASES
    privileged: true
    depends_on:
      - build-base
      - build-builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
